service: webscraping-github-jobs

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-dotenv-plugin

functions:
  extractJobsRepoBackendbr:
    handler: src/handlers/githubCrawler.getJobs
    events:
      - schedule: 
          rate: 'cron(*/1 * * * ? *)'

        

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
