service: poc-crud-lambda-function
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-offline-scheduler
  - serverless-dotenv-plugin

functions:
  getAllPosts:
    handler: src/handlers/githubCrawler.getJobs
    events:
      - schedule: rate(1 minutes)

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
